export const fonts = {
  stixNormal24: {
    fontFamily: 'STIXTwoText',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: '17px',
  },
  stixSemibold90: {
    fontFamily: 'STIXTwoText',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '90px',
    lineHeight: '85px',
  },
  montserratNormal14: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '17px',
  },
  montserratNormal24: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '24px',
    lineHeight: '36px',
  },
  montserratMedium16: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '25px',
  },
  montserratBold16: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '20px',
  },
  montserratNormal16: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '25px',
  },
  montserratSemibold40: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '40px',
    lineHeight: '49px',
  },
  montserratSemibold50: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '50px',
    lineHeight: '60px',
  },
  montserratSemibold28: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '28px',
    lineHeight: '34px',
  },
  montserratSemibold16: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '25px',
  },
  montserratSemibold32: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: '39px',
  },
  montserratMedium85: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '85px',
    lineHeight: '88px',
  },
  montserratMedium24: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '24px',
    lineHeight: '30px',
  },
};
